version: '3'
services:
  client:
    build:
      dockerfile: dev.Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
